n1 = int(input ("Enter first number: "))
n2 = int(input ("Enter second number: "))
n3 = int(input ("Enter third number: "))
n4 = int(input ("Enter fourth number: "))
n5 = int(input ("Enter fifth number: "))
n6 = int(input ("Enter sixth number: "))
n7 = int(input ("Enter seventh number: "))
n8 = int(input ("Enter eighth number: "))
unique = {n1,n2,n3,n4,n5,n6,n7,n8}
print (unique)
